### ISSUE TITLE
17. 쿠버네티스 애플리케이션개발을 위한 모범사례

### ISSUE THREAD

**Issue by sungsu9022** [sungsu9022/study-kubernetes-in-action#17]
# 17. 쿠버네티스 애플리케이션 개발을 위한 모범사례
## 17.1 쿠버네티스에서 애플리케이션의 구성
 - 하나의 애플리케이션을 쿠버네티스 클러스터 위에 동작시킨다고 했을때 아래와 같은 형태로 구성된다고 보면 된다.

<img width="664" alt="스크린샷 2020-09-28 오후 11 01 45" src="https://user-images.githubusercontent.com/6982740/94442151-98a13000-01de-11eb-82e1-8993034e016f.png">

 - 일반적은 앱은 하나 이상의 디플로이먼트나 스테이트풀셋 오브젝트를 포함한다.
 - 시크릿은 일반적으로 앱 개발자가 아니라 운영팀이 구성하기 때문에 파드에 직접 시크릿을 할당하지 않고 서비스어카운트를 통해 할당된다.
 - 경우에 따라 앱에서 잡이나 크론잡을 사용해야 할 때도 있으며, 데몬셋은 일반적으로 앱 디플로이먼트의 일부로 하지는 않고, 시스템 운영자가 노드 전체 또는 일부에 시스템 서비스를 실행하는 경우 사용한다.
 - 리소스는 종종 쳬계적으로 유지해야 하므로 하나 이상의 레이블을 필수로 지정하는 것이 좋다.
 - 각 리소스를 설명하거나 해당 담당자 또는 팀의 연락처 정보를 나열하기 위해 이를 어노테이션에 포함시킬 수 있다.

## 17.2 파드 라이프사이클 이해
 - 파드에서 실행 중인 애플리케이션은 언제든지 종료될 수 있기 때문에 이를 고려해야 한다.

### 17.2.1 애플리케이션을 종료하고 파드 재배치 예상하기
 - 쿠버네티스를 사용하면 애플리케이션이 훨씬 더 자주 자동으로 배치된다. 이는 개발자가 개발할때에도 고려애해야 함을 의미한다.

#### 로컬 IP와 호스트 이름 변경 예상하기
 - 파드가 종료되고 다른곳에서 실행되면 새로운 IP 주소와 새로운 이름, 호스트 이름을 갖는다는 사실을 알아야 한다.
 - 스테이트풀셋인 경우 호스트 이름이 변하지는 않지만 파드의 IP는 변경된다.
 - 그래서 개발자는 클러스터된 애플리케이션의 구성원을 IP 주소 기반으로 하면 안 된다.

#### 디스크에 기록된 데이터가 사라지는 경우 예상하기
 - 퍼시트턴트 스토리지를 마운트하지 않으면 앱이 새 파드로 시작된 후에 해당 데이터를 사용하지 못할 수 있다는 것을 알아야 한다.
    - 컨테이너가 다시 시작되면 완전히 새로운 쓰기 가능한 레이어로 시작되기 떄문에 이전 파일들은 모두 손실된다.
 - 프로세스 크래시나 라이브니스 프로브가 실패를 반환했거나 노드의 메모리 부족이 시작돼 프로세스가 OOMKiller에 의해 종료된 경우 등 다양한 이유로 컨테이너가 다시 시작될 수 있다. 이 경우 파드는 여전히 동일하지만 컨테이너 자체는 완전히 새로운 것이 된다.
    - kubelet은 동일한 컨테이너를 다시 실행하지 않고 항상 새 컨테이너를 만들기 떄문이다.

<img width="586" alt="스크린샷 2020-09-28 오후 11 11 33" src="https://user-images.githubusercontent.com/6982740/94443301-f5e9b100-01df-11eb-9312-46a55fd44e3e.png">

#### 컨테이너를 다시 사용하더라도 데이터 보존하기 위해 볼륨을 사용하라.
 - 데이터가 손실되지 않도록 하려면 최소한 파드 범위의 볼륨을 사용해야 한다.
 - 하지만 만약 볼륨에 저장된 데이터가 앱 구동에 필요한 상황이고, 이를 위해서 볼륨을 사용했을때 볼륨에 저장된 파일이 손상되었다면 새로 생성된 프로세스가 실행 도중 크래시된다면 연속 크래시 루프가 발생할 수도 있다.(파드의 CrashLoopBackOff 상태)

<img width="595" alt="스크린샷 2020-09-28 오후 11 12 35" src="https://user-images.githubusercontent.com/6982740/94443408-1ade2400-01e0-11eb-9495-1aa6012977c0.png">

### 17.2.2 종료된 파드 또는 부분적으로 종료된 파드를 다시 스케줄링하기
 - 파드의 컨테이너가 계속 크래시되면 kubelet은 파드를 재시작한다. 이 간격은 지수시간으로 증가하다가 최대 5분까지 증가한다.(10초, 20초, 40초, ...)
 - 파드에 여러개의 컨테이너가 있고 그 중에 하나의 컨테이너가 크래시하기 시작한다면 어떻게 될까? 
   - 이 경우 테이너의 재시작 간격을 늘리면서 컨테이너를 재실행할 것이다.
   - 하지만 레플리카셋 컨트롤러에서는 컨테이너가 재실행되는동안(CrashLoopBackOff) 새로운 파드를 스케줄링하지 않는다.
       - 레플리카셋 컨트롤러는 파드 수가 의도하는 레플리카 수와 일치하는지만 보기 때문이다.

<img width="538" alt="스크린샷 2020-09-28 오후 11 16 08" src="https://user-images.githubusercontent.com/6982740/94443834-99d35c80-01e0-11eb-8e5e-685a6667c32f.png">

#### 파드가 계속 크래시하는 레플리카셋을 배포한 뒤 결과
 - 파드는 계속 CrashLoopBackOff 상태가 표시되고, 레플리카수와 레플리카가 일치하기 때문에 컨트롤러는 별도의 조치를 하지 않는다. 

<img width="639" alt="스크린샷 2020-09-28 오후 11 21 48" src="https://user-images.githubusercontent.com/6982740/94444560-69d88900-01e1-11eb-91ba-14e99d0a4e4f.png">

 - 쿠버네티스가 위와 같은 상황에서 파드를 다른 노드로 리스케줄하지 않는 이유는 앱이 컨테이너 안에서 실행된다면 모든 노드가 거의 비슷한 조건일 가능성이 높으므로 다른 노드로 파드를 스케줄링하더라도 문제가 해결될 가능성이 적기 때문이다.

#### 파드 시작 방법
 - 쿠버네티스에서는 파드 애플리케이션 여러 개를 실행할 때 쿠버네티스가 특정 파드를 먼저 실행하고 첫 번째 파드가 서비스할 준비가 됐을 때 나머지 파드를 실행하도록 지시할 방법은 기본적으로 제공하지 않는다.
    - YAML에 여러개 리소스를 등록하더라도 파드가 그 순서대로 시작된다는 보장이 없다.
 - 하지만 초기화 컨테이너(init-container) 기능을 이용한다면 특정 파드들의 구동순서를 보장시킬 수 있다.

#### 초기화 컨테이너(init-container)
 - 초기화 컨테이너의 이름에서 알수 있듯이 본 목적은 파드의 주 컨테이너를 구동시키기 전에 초기화하는 것을 못적으로 한다.
 - 파드는 여러 개의 초기화 컨테이너를 가질 수 있고, 이는 순차적으로 실행되며 마지막 컨테이너가 완료된 후에 주 컨테이너가 시작된다.
 - 이를 통해 파드A와 파드B가 있을때 파드B의 초기화 컨테이너에서 A의 구동을 기다리도록 한다면 파드 A,B의 구동 순서를 보장할 수 있다.

#### 파드의 초기화 컨테이너 추가
``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: fortune-client
spec:
  initContainers:      # 일반 컨테이너가 아닌 초기화 컨테이너를 정의
  - name: init
    image: busybox
    command:
    - sh
    - -c
    - 'while true; do echo "Waiting for fortune service to come up..."; wget http://fortune -q -T 1 -O /dev/null >/dev/null 2>/dev/null && break; sleep 1; done; echo "Service is up! Starting main container."'
  containers:
  - image: busybox
    name: main
    command:
    - sh
    - -c
    - 'echo "Main container started. Reading fortune very 10 seconds."; while true; do echo "-------------"; wget -q -O - http://fortune; sleep 10; done'
```

#### 초기화 컨테이너 구동
 - 초기화 컨테이너를 가진 파드를 구동시키고 파드 상태를 조회해보면 Status에 ```Init:0/1``` 와 같은 형태를 볼 수 있다. 이는 초기화 컨테이너 1개 중 0개가 완료됐음을 나타낸다. 
 - kubectl logs를 이용해서 컨테이너를 지정하고 초기화 컨테이너의 로그를 확인할 수 있다.

<img width="425" alt="스크린샷 2020-09-28 오후 11 32 38" src="https://user-images.githubusercontent.com/6982740/94445857-e91a8c80-01e2-11eb-9827-ff22411c465e.png">

#### 파드 간 의존성 처리를 위한 모범 사례
 - 애플리케이션이 시작되기 전 준비 상태가 되기 위해 의존해야 할 서비스를 필요로 하지 않도록 애플리케이션을 만드는 것이 가장 좋다.
 - 애플리케이션 의존성이 있다면 이를 위해 레디니스 프로브를 통해 의존성이 완료되어 정상 응답을 줄수 있을때 서비스에 투입되도록 하는것이 바람직하다.

### 17.2.4 라이프사이클 훅
 - 파드는 시작 후 훅(post-start hook), 종료 전 훅(pre-stop hook) 이 2가지를 정의할 수 잇다.
 - 훅에서 정의할 커맨드는 라이브니스 프로브나 레디니스 프로브와 유사하게 컨테이너 내부에서 명령을 실행하거나 url로 http get 요청 등을 수행할 수 있다.

#### 컨테이너의 시작 후 라이프사이클 훅 사용
 - 주 프로세스가 시작된 직후에 실행된다. 애플리케이션이 시작될 떄 추가 작업을 수행하는 데 사용하면 된다.
 - 애플리케이션 코드를 수정하지 않고 무언가 추가적인 명령을 수행해야 하는 경우에 적절하게 사용할 수 있다.
 - 훅은 주 프로세스와 병렬로 비동기적으로 수행됨을 알아야 한다. 주 프로세스가 아직 구동전이더라도 라이프사이클 훅이 바로 동작할 수 있다.
 - 훅이 실행되는 동안 컨테이너는 ContainerCreating인 채로 Waiting 상태를 유지한다는 점도 알아야 한다. 이로 인해 파드는 Running중이 아니라 Pending 상태가 된다. 훅이 실행되지 않거나 0이 아닌 종료 코드를 반환하면(오류로 인한 종료)라면 주 컨테이너가 종료된다.

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-poststart-hook
spec:
  containers:
  - image: luksa/kubia
    name: kubia
    lifecycle:
      postStart:          # 컨테이너가 시작될 떄 훅이 실행된다.
        exec:
          command:
          - sh
          - -c
          - "echo 'hook will fail with exit code 15'; sleep 5 ; exit 15"
```
 
 - 라이프사이클 훅은 표준 출력에 로그가 남지 않아서 디버깅이 어려운 점을 가지고 있다. 훅이 실패하면 파드의 이벤트 중 FailedPostStartHook 경고만 표시된다.
 - 명령어 기반인 시작 후 훅의 표준 출력과 표준 오류 출력은 어다에도 로깅되지 않기 때문에 훅 호출 프로세스를 컨테이너의 파일시스템에 있는 파일에 기록하고 파일 내용을 확인할 수 있도록 하는 것이 좋다. 이를 위해 emptyDir 볼륨을 마운트하고 훅이 이 볼륨에 로그를 쓰도록 하는것을 권장한다.

#### 컨테이너의 종료 전 라이프사이클 훅 사용
 - 컨테이너가 종료되기 직전에 종료 전 훅이 실행된다.
 - 컨테이너를 종료해야 할 경우 kubelet은 종료 전 훅을 실행한 다음 SIGTERM을 전송한다.
 - 컨테이너가 SIGTERM 신호를 수신해도 정상적으로 종료되지 않으면 종료 전 훅을 사용해 컨테이너를 정상적으로 종료할 수 있다.

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-prestop-hook
spec:
  containers:
  - image: luksa/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
    lifecycle:
      preStop:            # 종료 전 훅 정의
        httpGet:          # 종료전훅에서 http get 요청을 수행한다.
          port: 8080
          path: shutdown
```

 - 종료전 훅은 실패하면 파드의 이벤트 중에 FailedPreStopHook 경고 이벤트가 표시되지만 곧 파드가 삭제되기 때문에 종료 전 훅이 재대로 작동하지 않았다는 것을 알기 어려울 수 있으니 주의해야 한다.(꼭 성공해야만 전체 시스템에 이상이 없을 경우 로그 등을 통해 철저히 확인하는 것이 좋다)

#### 애플리케이션이 SIGTERM 신호를 수신하지 않기 때문에 종료 전 훅 사용
 - 컨테이너 이미지가 셸을 실행하도록 구성되어있고, 셸에서 애플리케이션 프로스세를 실행하는경우 자식 프로세스로 SIGTERM 신호가 전달되지 않고 셸 자체에서 신호를 차단할 수 있다.
 - 컨테이너 이미지가 셸을 실행하지 않고 애플리케이션 바이너리를 직접 실행하도록 구성한다면 이런 문제가 사라진다.
     - Dockerfile의 ENTRYPOINT 또는 CMD에 exec 형식인 ```ENTRYPOINT /binary``` 대신 ```ENTRYPOINT ["/binary"]``` 을 사용

#### 파드가 아닌 컨테이너를 타깃으로 하는 라이프사이클 훅 이해
 - 시작 후(post-start)와 종료 전(pre-stop) 라이프사이클 훅은 파드가 아닌 컨테이너와 관련되어 있음을 명심해야 한다.
 - 그렇기 때문에 파드가 종료되는 동안 뿐만 아니라 파드 라이프사이클 동안 여러번 이 훅이 발생할 수 있다.

### 17.2.5 파드 셧다운 이해하기
 - 파드에서 실행되는 애플리케이션을 완전히 종료하는 방법을 이해하는 것도 중요하다.
 - HTTP DELETE 요청이 생기면 API 서버는 오브젝트를 삭제하는 것이 아니라 그 안의 deleteTimestamp 필드를 설정한다. 그리고 이 필드가 설정된 파드가 종료된다.
     - 이 종료는 kubelet이 수행하고, deleteTimestamp 필드를 확인하면 각 파드의 컨테이너를 종료하기 시작한다.
 - 각 컨테이너에 정상적으로 종료하는 데 걸리는 시간은 제한되어있다. 이를 종료 유예 기간(termination grace period)라고 하며 파드별로 이를 구성할 수 있다.

#### 파드가 종료되는 과정
1. 종료 전 훅(구성된 경우)을 실행하고 완료될 때까지 기다린다.
2. SIGTERM 신호를 컨테이너의 주 프로세스로 보낸다.
3. 컨테이너가 완전히 종료될 때까지 또는 종료 유예 기간이 끝날 때까지 기다린다.
4. 아직 정상적으로 종료되지 않은 경우 SIGKILL로 프로세스를 강제 종료한다.

<img width="595" alt="스크린샷 2020-09-29 오후 10 49 04" src="https://user-images.githubusercontent.com/6982740/94567013-fc426080-02a5-11eb-96a6-b89d1a417ea2.png">

#### 종료 유예 기간 지정
 - 파드 스펙의 terminateGracePeriodSeconds 필드로 설정할 수 있따.
 - 기본값은 30이고, 강제 종료되기 전에 정상 종료할 수 있도록 30초가 주어진다는 의미이고, 30초 이후에는 컨테이너 주 프로세스를 강제 종료시킨다.
 - 이 값을 설정할 경우 프로세스가 시간 내에 정상 종료될 수 있도록 유예 기간을 충분히 길게 설정하는 것이 좋다.

#### 리소스를 즉시 삭제하는 방법

``` sh
# 파드의 종료 유예 기간 재정의
# --grace-period=${seconds} 를 통해 파드의 종료 유예 기간을 재정의하면서 종료시킬 수 있다.
kubectl delete po mypod --grace-period=5

# 강제로 즉시 종료
# --force 옵션을 추가해 확인을 기다리지 않고 API 서버가 리소스를 즉시 삭제할 수 있다.
kubectl delete po mypod --grace-period=0 --force
```

 - 이러한 ```--force```` 옵션을 사용할 때 파드가 스테이트풀셋이라면 주의해야 한다. 이런 처리를 하다가 동일한 파드의 두 인스턴스가 동시에 실행되어 스테이트풀 클러스터가 오작동할지도 모른다.

#### 애플리케이션에서 적절한 셧다운 핸들러 구현
 - 애플리케이션이 완전히 종료되는 데 걸리는 시간을 예측할 수 없다면 종료 단계에서 파드는 모든 데이터를 나머지 파드로 마이그레이션하는 등 적절한 조치를 통해 데이터가 손실되지 않도록 해야 한다.
 - 컨테이너가 종료해도 파드 전체가 종료되는 것은 아니고, 프로세스가 종료되기 전 종료 절차가 끝난 것이라는 보장이 없기 떄문에 파드가 종료 신호를 수신하는 시점(SIGTERM 또는 종료 전 훅으로)에 이런 처리를 해서는 안된다.

#### 전용 셧다운 절차 파드를 사용해 중요한 셧다운 절차 대체
 - 애플리케이션이 새 파드를 실행하는 새로운 잡 리소스를 만드는 것이다. 그 역할은 삭제된 파드의 데이터를 나머지 파드로 옮기는 것이다.
    - 이 경우에도 노드가 실패하면 방법이 없기는 하다.
 - 위 문제 해결을 위해서는 분산된 데이터의 존재를 확인하는 전용 파드를 항상 실행하는 방법이 있다. (크론잡 리소스 등을 이용)
 - 스테이트풀셋을 사용했을 떄 이를 보장할 수 있을거라고 생각할 수 있지만 그렇지 않다. 스케일 다운될 경우에는 퍼시스턴트볼륨은 그대로 남아있고 다시 스케일 업이 되지 않으면 데이터에 누구도 접근할 수 없다. 그러므로 이러한 마이그레이션 처리가 필요하다.

<img width="475" alt="스크린샷 2020-09-29 오후 10 59 52" src="https://user-images.githubusercontent.com/6982740/94568487-7e7f5480-02a7-11eb-9664-f6886f44c862.png">

## 17.3 모든 클라이언트 요청의 적절한 처리 보장
 - 파드의 클라이언트 관점에서 파드의 라이프 사이클을 살펴볼 필요가 있다.
 - 파드의 스케일업과 스케일다운 과정 중에 모든 클라이언트 요청이 올바르게 처리되어야 할 것이다. 이를 위해서는 연결이  끊어지지 않도록 애플리케이션에서 몇 가지 규칙을 잘 따라야 한다.

### 17.3.1 파드가 시작될 때 클라이언트 연결 끊김 방지
 - 파드 스펙에 레디니스 프로브를 지정하지 않으면 곧바로 파드는 항상 준비된 것으로 간주되기 떄문에 이를 필수적으로 지정해야 한다.
 - 레디니스 프로브에서는 요청을 올바르게 처리할 준비가 됐을 때에만 레디니스 프로브가 성공을 반환하도록 해야 한다.

#### 파드 삭제시 발생하는 이벤트의 순서
 - 클라이언트로부터 파드 삭제 요청이 들어오면 다음과 같은 순서로 동작이 일어난다.
 - 파드 삭제에 대한 알림은 이를 감시하던 워커 노드로 전달되고 kubelet은 파드를 종료를 수행한다. 
 - 엔드포인트 컨트롤러는 파드가 삭제됐다는 알림을 받으면 파드가 속한 모든 서비스의 엔드포인트에서 파드를 제거한다. 그리고 각 프록시는 노드의 iptables 규칙을 업데이트해 새 연결이 종료되는 파드로 전달되지 않도록 한다.
    - 여기서 iptables 규칙을 제거해도 기존 연결에는 영향을 미치지 않는다.(파드에 이미 연결된 클라이언트는 기존 연결로 파드에 추가 요청을 계속 보낸다.)

<img width="668" alt="스크린샷 2020-09-29 오후 11 03 58" src="https://user-images.githubusercontent.com/6982740/94568912-12512080-02a8-11eb-842e-50f0d7e43634.png">

 - 시간의 흐름 순서로 본다면 다음과 같다.

<img width="685" alt="스크린샷 2020-09-29 오후 11 08 45" src="https://user-images.githubusercontent.com/6982740/94569537-c94d9c00-02a8-11eb-90e1-950be6ed5369.png">

 - 결과적으로 파드는 종료 신호를 보낸 후에도 클라이언트 요청을 받을 수 있다. 애플리케이션이 서버 소켓을 닫고 연결 수락을 즉시 중지한다면 클라이언트는 Connection Refused 에러를 수신하게 될 것이다.

#### 문제 해결
 - 위에서 설명한 것처럼 일련의 과정이 비동기적으로 일어나기 때문에 모든 kube-proxy가 iptables 규칙을 업데이트하기전까지는 종료 신호를 수신하더라도 파드가 연결을 계속 수락해야 하는 상황이 생긴다. 
 - 어떤 클라이언트도 연결이 끊어지지 않도록 하려면 더 이상 파드에 대한 연결을 전달하지 않겠다고 알릴 때까지 기다려야 한다.
 - 하지만 모든 구성요소가 여러 컴퓨터에 분산되어 있기 때문에 이는 불가능하다. 
 - 결국 가장 좋은 해결방법은 모든 프록시가 자신의 작업을 완료할 수 있도록 충분한 시간을 기다리는 것 뿐이다.
    - 완벽히 모든 클라이언트 연결을 끊어지지 않도록 할 수는 없겠지만 이 지연시간을 5~10초 정도 추가한다면 사용자 경험이 상당히 향상될 수 있다. 
    - 쿠버네티스를 사용하지 않는 일반적인 서비스에서도 이와 비슷한 처리를  한다.

#### 애플리케이션을 적절히 종료하는 과정
 - 몇 초를 기다린 후, 새 연결을 받는 것을 제한한다.
 - 요청 중이 아닌 모든 ㅇ녀결 유지 연결(keep-alive connections)을 닫는다.
 - 모든 활성 요청(active request)이 완료될 때까지 기다린다.
 - 그런 다음 완전히 셧다운 한다.

<img width="676" alt="스크린샷 2020-09-29 오후 11 14 35" src="https://user-images.githubusercontent.com/6982740/94570201-8cce7000-02a9-11eb-836b-18706dc89b8c.png">

``` yaml
# 최소한 몇초 동안 대기하는 종료 전 훅을 추가하는 것도 가장 좋은 방법중에 하나이다.
    lifecycle:
      preStop:
        exec:
          command:
          - sh
          - -c
          - "sleep 5"
```

### 17.4.1 관리 가능한 컨테이너 이미지 만들기
 - 이미지를 만들때 OS 배포판의 모든 파일을 다 넣을 필요는 없다. 다 넣을 경우 파드가 노드에 처음 스케줄링할 때 필요 이상으로 대기해야 하는 경우가 생길 수 있다.
    - 컨테이너 레지스트리에서 이미지 다운로드 시간이 증가할 수 있기 때문
 - 불필요한 것이 없는 작은 이미지로 만드는 것이 중요하다.
 - 하지만 최소한의 이미지로는 디버깅이 어렵기 때문에 컨테이너 내에 ping,dig, curl 또는 이와 유사한 도구 등은 이미지에 포함시켜주는 것이 좋다.

#### 17.4.2 이미지에 적절한 태그를 지정하고 imagePullPolicy를 현명하게 사용하자
 - 파드 매니페스트에서 latest 태그를 참조하면 개별 파드 레플리카가 실행중인 이미지 버전을 알 수 없기 떄문에 이를 사용해서는 안된다.
    - latest 태그 아래에 이미지의 새 버전을 푸시하고 파드가 리스케줄링된다면 이전파드와 새로 스케줄링된 파드의 이미지 버전이 달라지게 된다.
 - 개발을 제외하고는 latest 버전 대신 적절한 버전 지정자를 포함하는 태그를 사용해야 한다. 변경 가능한 버전이라면 파드 스펙의 imagePullPolicy 필드를 always로 설정하면 된다.

#### imagePullPolicy가 always일때 주의사항
 - 새 파드가 배포될 떄마다 커네이너 런타임이 이미지 레지스트리에 접속해서 이미지를 가져와야 해서 파드 시작 속도가 약간 느려질 수 있다.
 - 그리고 혹시 레지스트리에 연결할 수 없는 상황에서는 파드를 시작할 수 없게 된다.

### 17.4.3 일차원 레이블 대신 다차원 레이블 사용
 - 파드 뿐만 아니라 모든 리소스에 레이블을 지정해야 한다.

#### 레이블에 포함시키면 좋은 항목
 - 리소스가 있는 애플리케이션(마이크로서비스)의 이름
 - 애플리케이션의 계층(back-end, front-end 등)
 - 환경(개발, QA, 스테이징, 프로덕션 등)
 - 버전
 - 릴리스 유형(안정 버전, 카나리, 블루-그린 디플로이먼트의 blue, green 등)
 - 테넌트(네임스페이스 대신 각 테넌트마다 별도의 파드를 실행하는 경우)
 - 샤드된 시스템용 샤드(shard)

### 17.4.4 어노테이션으로 각 리소스 설명
 - 최소한 리소스에는 리소스를 설명하는 어노테이션과 담당자 연락처 정보가 포함된 어노테이션을 포함시켜주는 것이 좋다.
 - MSA에서 파드는 사용 중인 다른 서비스의 이름을 나열하는 어노테이션을 포함할 수 있다.(이를 통해 파드간 의존성을 표시할 수 있다.)
 - 레이블과 어노테이션을 사용하면 실행 중인 애플리케이션을 쉽게 관리할 수 있다.

### 17.4.5 포르세스가 종료된 원인에 대한 정보 제공
 - 컨테이너가 왜 종료되었는지를 추적하는 일은 무언가 해놓지 않았다면 굉장히 추적이 어렵다. 그렇기 때문에 로그 파일에 필요한 모든 디버그 정보를 포함시켜두는 것이 좋다.
 - 프로세스가 컨테이너의 파일시스템에 있는 특정 파일에 종료 메시지를 작성하도록 할 수 있다. 그리고 컨테이너가 종료될 떄 이 파일의 내용을 kubelet에서 읽어서 kubectl describe pod에 표시되도록 할 수 있다.
 - 프로세스가 작성할 기본 파일은 ```/dev/termination-log``` 이고, 파드 스펙의 컨테이너 정의에서 terminationMessagePath 필드를 통해 직접 설정할 수 있다.

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-termination-message
spec:
  containers:
  - image: busybox
    name: main
    command:
    - sh
    - -c
    - 'echo "I''ve had enough" > /var/termination-reason ; exit 1'   # 컨테이너는 종료 직전 파일에 메시지를 쓴다.
    terminationMessagePath: /var/termination-reason               # 컨테이너 정보에 표시할 메시지 파일의 경로 재정의
```

<img width="1082" alt="스크린샷 2020-09-29 오후 11 32 42" src="https://user-images.githubusercontent.com/6982740/94572556-20a13b80-02ac-11eb-98ca-4fb63977bc7a.png">

 - 이 방식은 크래시가 발생이 아닌 일반적인 완료 가능한 작업을 실행하고 성공적으로 종료되는 파드에도 적용할 수 있다.
 - 커테이너가 메시지를 파일에 쓰지 않으면 terminationMessagePolicy 필드를 FallbackToLogsOnError로 설정하면 컨테이너 로그의 마지막 몇 줄이 종료 메시지로 사용된다.(이는 비정상 종료인 경우에만 해당)

### 17.4.6 애플리케이션 로깅 처리
 - 일반적으로 ```kubectl logs``` 명령어로 로그를 쉽게 볼 수 있다. ```--previous``` 옵션을 사용하면 이전 컨테이너의 로그를 볼수도 있따.
 - 표준 출력 대신 파일에 로깅하는 경우 ```kubectl exec <pod> cat <logfile>``` 을 통해서 로컬에서 바로 로그를 조회할 수도 있다.

#### 컨테이너의 로그 및 기타 파일 복사
 - ```kubectl cp``` 명령어를 사용해 로그 파일을 로컬 시스템에 복사할 수도 있다.

``` sh
#  단일 컨테이너 파드 foo-pod의 로그(/var/log/foo.log)를 로컬로 복사
kubectl cp foo-pod:/var/log/foo.log foo.log

#  로컬 파일을 파드로 전달
kubectl cp localfile foo-pod:/etc/remotefile

# 컨테이너가 둘 이상인 경우 -c containerName 옵션을 사용할 수 있다.
```

#### 중앙 집중식 로깅
 - ElasticSearch, LogStash, Kibana로 구성된 ELK 스택 또는  EFK 스택(ElasticSearch, FluentD, Kibana)을 통해 중앙 집중식 로깅을 할수도 있따.
 - EFK 스택을 사용할 경우 쿠버네티스 클러스터 노드는 FluentD 에이전트(일반적으로 데몬셋으로 배포)을 실행하고, 이는 컨테이너에서 로그를 수집하고 파드 관련 정보로 태그를 지정해 전달한다. 
 - ElasticSearch는 클러스터 어딘가에 배포되어 FluentD 에이전트로부터 전달받은 데이터를 저장하고, 
 - Kibana를 통해 시각화 처리를 한다. 
 - 이런 애플리케이션들은 파드로 실행되고 서비스로 노출시킨다.

<img width="593" alt="스크린샷 2020-09-29 오후 11 42 50" src="https://user-images.githubusercontent.com/6982740/94573908-817d4380-02ad-11eb-965b-00126ebc7418.png">

#### 여러 줄로 구성된 로그 문구 처리
 - 자바의 예외 스택 트레이스와 같이 여러 줄에 걸쳐 있는 로그는 중앙 로깅 시스템에서 별도의 항목으로 나타날 수 있다. 이 문제를 해결하기 위해서 애플리케이션이 일반 텍스트 대신 JSON을 출력하도록 하는 것도 방법이다.(하지만 kubectl logs 명령어로 볼떄는 읽기 친화적이지 않다.)

#### 백엔드 서비스 연결
 - 로컬 시스템에서 쿠버네티스 클러스터에 배포된 백엔드 서비스에 연결하기 위해서 여러가지 방법이 있다.
 - 로컬 시스템에서 각 서비스에 연결을 위한 환경변수를 수동으로 HOST 설정 등을 통해 설정하고 실행 중인지 여부에 관계 없이 백엔드 서비스를 가르키게 하는 방법이 있다.

#### API 서버에 연결
 - 서비스 어카운트의 토큰을 사용해 자체 인증하는 경우 kubectl cp를 사용해 서비스어카운트의 시크릿 파일을 로컬 컴퓨터에 복사하여 사용할 수 있다.
 - 아니면 로컬 컴퓨터에서 kubectl proxy를 실행하고 로컬로 애플리케이션을 실행하면 로컬 kubectl proxy를 통해 통신할 수 있다.

#### 개발 중 컨테이너 내부에서 실행
 - 바이너리를 이미지에 굽는 대신 도커 볼륨으로 로컬 파일시스ㅔㅁ을 컨테이너에 항상 마운트하는 방버을 사용할 수 있다.
     - 이렇게 하면 이미지를 다시 만들지 않고 컨테이너를 재시작하기만 하면 된다.
     - hot-redeploy가 지원되는 경우라면 컨테이너조차 재시작하지 않아도 된다.

### 17.5.2 개발 중 Minikube 사용
 - Minikube 클러스터는 워커 노드 하나만 실행하지만 쿠버네티스에서 애플리케이션을 시험해볼 수 있는 아주 유요한 방법이다.

#### Minikube 가상머신과 로컬 컨테이너로 로컬 파일 마운트
 - ```minikube mount``` 명령어를 사용해 로컬 파일시스템을 minikube 가상머신에 마운트한 다음 hostPath로 컨테이너에 마운트할 수 있따.

#### 로컬 파일을 minikube 가상 머신에 마운트한 후 컨테이너에 넣기
 - minikube의 도커 데몬을 사용하려면 DOCKER_HOST 환경변수를 지정하기만 하면 바로 사용할 수 있따.

``` sh
$ eval $(minikube docker-env)
```

#### 로컬에서 이미지를 빌드하고 minkube 가상머신에 직접 복사

``` sh
docker save <image> | (eval $(minikube docker-env) && docker load)
```

 - 이 경우 파드 스펙의 imagePullPolicy가 always이면 이미지를 외부 레지스트리에서 다시 가져오게 되어 복사한 내용이 손실 될 수 있으니 주의해야 한다.

#### 적절한 쿠버네티스 클러스터와 minikube 결합
 - 애플리케이션 개발이 끝나면 쿠버네티스가 기본 인프라를 잘 추상화한 덕분에 로컬 워크로드를 수정 없이 원격 클러스터로 문제없이 옮길 수 있다.

### 17.5.3 버전 관리 및 자동 배포 리소스 매니페스트
 - 쿠버네티스는 선언적 모델을 사용하므로 의도하는 상태로 변경 가능.
 - 버전 관리 시스템에 리소스 매니페스트를 저장. 필요 시마다 변경 사항을 적용/롤백 가능.
 - 여러 브랜치를 사용해 매니페스트를 개발, QA, 스테이징, 프로덕션 클러스터에 배포하도록 한다.
 - kube-applier 라는 도구가 있으나 2019년 이후로 관리가 되지 않고 있어서 사용하는 것은 권장되지는 않아보인다.

### 17.5.4 YAML/JSON 매니페스트의 대안 Ksonnet
 - 매개변수화된 JSON을 정의하고 이름을 지정한 다음 여러 위치에서 동일한 JSON 코드를 반복하는 대신 이름으로 해당 JSON을 참조해 전체 JSON 매니페스트를 빌드하는 도구
 - 훨씬 적은 코드로 완전한 쿠버네티스 리소스 JSON 매니페스트를 빠르게 작성할 수 있다.
 - Ksonnet과 Jsonnet의 장점은 더 높은 수준의 조각을 정의하고 모든 매니페스트를 일관되고 중복 없이 만들 수 있다는 것이다.
 - 개인적인 생각으로는 가독성이 떨어진다고 느껴진다..

``` ksonnet
local k = import "../ksonnet-lib/ksonnet.beta.1/k.libsonnet";

local container = k.core.v1.container;
local deployment = k.apps.v1beta1.deployment;

local kubiaContainer =                                          # luksa/kubia:v1 이미지를 사용하고 http 포트를 포함하는 kubia 라는 컨테이너 정의
  container.default("kubia", "luksa/kubia:v1") +
  container.helpers.namedPort("http", 8080);

deployment.default("kubia", kubiaContainer) +   # 디플로이먼트 리소스로 확장
deployment.mixin.spec.replicas(3)
```

### 17.5.5 지속적 통합과 지속적 배포
 - 완전한 지속적 통합과 지속적 배포(CI/CD, Continuous Integration / Continuous Delivery) 파이프라인을 설정할 수 있다.
 - 쿠버네티스를 위한 통합 개발 플랫폼인 Fabric8이라는 것이 있다.
 - 데브옵스(DevOps) 스타일의 마이크로서비스 개발, 배포, 관리를 위한 전체 CI/CD 파이프라인을 제공하려고 잘 알려진 오픈소스 자동화 시스템인 젠킨스와 기타 다양한 도구가 포함되어 있다.

## Reference
 - [https://github.com/box/kube-applier](https://github.com/box/kube-applier)
 - [http://fabric8.io/](http://fabric8.io/)
